SuperHero/Models/ErrorViewModel.cs
using System;

namespace SuperHero.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SuperHero/Models/Superhero.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SuperHero.Models
{
    public class Superhero
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public string AlterEgo { get; set; }
        public string PrimaryAbility { get; set; }
        public string SecondaryAbility { get; set; }
        public string CatchPhrase { get; set; }
    }
}

SuperHero/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SuperHero.Models;
using Microsoft.EntityFrameworkCore;
using SuperHero.Data;

namespace SuperHero.Controllers
{
    public class HomeController : Controller
    {
        
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SuperHero/Controllers/SuperheroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SuperHero.Data;
using SuperHero.Models;

namespace SuperHero.Controllers
{
    public class SuperheroController : Controller
    {
        private ApplicationDbContext _context;
        public SuperheroController(ApplicationDbContext context)
        {
            _context = context;
        }
        
        public ActionResult Index()
        
        {
            var superheroes = _context.Superheroes.ToList();
            return View(superheroes);
        }
        
        public ActionResult Details(int id)
        {
            var hero = _context.Superheroes.Where(m => m.Id == id).SingleOrDefault();
            return View(hero);
        }
        

        [HttpGet]
        public ActionResult Create()
        {
            var hero = new Superhero();
            return View(hero);
        }
        [HttpPost]
        public ActionResult Create(Superhero hero)
        {
            _context.Superheroes.Add(hero);
            _context.SaveChanges();
            return RedirectToAction("index");         
        }
        
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var hero = _context.Superheroes.Where(m => m.Id == id).SingleOrDefault();
            return View(hero);
        }
        [HttpPost]
        public ActionResult Edit(Superhero hero)
        {
            _context.Superheroes.Update(hero);
            _context.SaveChanges();
            return RedirectToAction("index");
        }

        
        
        [HttpGet]
        public ActionResult Delete(int id)
        {
            var hero = _context.Superheroes.Where(m => m.Id == id).SingleOrDefault();
            return View(hero);
        }
        [HttpPost]
        public ActionResult Delete(Superhero hero)
        {
            _context.Superheroes.Remove(hero);
            _context.SaveChanges();
            return RedirectToAction("index");
        }
                      
        
    }
}

SuperHero/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about some of my favorite superheroes!</p>
    <img src="https://d2jv9003bew7ag.cloudfront.net/uploads/My-Mask1-865x577.jpg" alt="superbat pic" width="400">
</div>

SuperHero/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SuperHero</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SuperHero</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Superhero" asp-action="Index">Superheroes</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - SuperHero - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

SuperHero/Views/Superhero/Create.cshtml
@model SuperHero.Models.Superhero

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Superhero</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AlterEgo" class="control-label"></label>
                <input asp-for="AlterEgo" class="form-control" />
                <span asp-validation-for="AlterEgo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrimaryAbility" class="control-label"></label>
                <input asp-for="PrimaryAbility" class="form-control" />
                <span asp-validation-for="PrimaryAbility" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SecondaryAbility" class="control-label"></label>
                <input asp-for="SecondaryAbility" class="form-control" />
                <span asp-validation-for="SecondaryAbility" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CatchPhrase" class="control-label"></label>
                <input asp-for="CatchPhrase" class="form-control" />
                <span asp-validation-for="CatchPhrase" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

SuperHero/Views/Superhero/Delete.cshtml
@model SuperHero.Models.Superhero

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Superhero</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AlterEgo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AlterEgo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PrimaryAbility)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PrimaryAbility)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SecondaryAbility)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SecondaryAbility)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CatchPhrase)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CatchPhrase)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

SuperHero/Views/Superhero/Details.cshtml
@model SuperHero.Models.Superhero

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Superhero</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AlterEgo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AlterEgo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PrimaryAbility)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PrimaryAbility)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SecondaryAbility)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SecondaryAbility)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CatchPhrase)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CatchPhrase)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

SuperHero/Views/Superhero/Edit.cshtml
@model SuperHero.Models.Superhero

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Superhero</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AlterEgo" class="control-label"></label>
                <input asp-for="AlterEgo" class="form-control" />
                <span asp-validation-for="AlterEgo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrimaryAbility" class="control-label"></label>
                <input asp-for="PrimaryAbility" class="form-control" />
                <span asp-validation-for="PrimaryAbility" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SecondaryAbility" class="control-label"></label>
                <input asp-for="SecondaryAbility" class="form-control" />
                <span asp-validation-for="SecondaryAbility" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CatchPhrase" class="control-label"></label>
                <input asp-for="CatchPhrase" class="form-control" />
                <span asp-validation-for="CatchPhrase" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

SuperHero/Views/Superhero/Index.cshtml
@model IEnumerable<SuperHero.Models.Superhero>

@{
    ViewData["Title"] = "Index";
}

<h1>Some superheroes, for example...</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>